#!/bin/bash

resX=$(xdpyinfo | grep dimensions | awk '{print $2}' | cut -d "x" -f 1)
resY=$(xdpyinfo | grep dimensions | awk '{print $2}' | cut -d "x" -f 2)

echo dimensions "$resX"x"$resY"

if [[ $1 == */* ]]; then
	perX=$( echo $1 | cut -d "/" -f 1 )
	perX=$(( $perX * 100 ))
	perX=$(( $perX / $( echo $1 | cut -d "/" -f 2) ))
else
	perX=$1
fi

if [[ $2 == */* ]]; then
	perY=$( echo $2 | cut -d "/" -f 1 )
	perY=$(( $perY * 100 ))
	perY=$(( $perY / $( echo $2 | cut -d "/" -f 2) ))
else
	perY=$2
fi

echo scale "$perX"x"$perY"

winX=$(( ($resX * $perX) / 100 ))
winY=$(( ($resY * $perY) / 100 ))

echo window size "$winX"x"$winY"

i3-msg floating enable
i3-msg resize set $winX px $winY px